services:
  qwen-model:
    image: vllm/vllm-openai:latest
    container_name: server-qwen
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ipc: host
    environment:
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    command: >
      --model Qwen/Qwen2-VL-2B-Instruct
      --gpu-memory-utilization 0.80
      --max-model-len 8192
      --enable-auto-tool-choice
      --tool-call-parser hermes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
